[tasks.build_pi]
description = "Build the project for the raspberry pi"
command = "cargo"
args = ["build", "--target=armv7-unknown-linux-gnueabihf", "--features=vendored"]


[tasks.bundle]
description = "Bundles the project into a zip file"
dependencies = ["build_pi"]
script = [
    "zip -r desktopper.zip resources/ target/armv7-unknown-linux-gnueabihf/debug/desktopper target/armv7-unknown-linux-gnueabihf/debug/api_server"
]

[tasks.deploy]
description = "Deploys the project to the raspberry pi"
dependencies = ["bundle"]
script = [
    "scp desktopper.zip pi@desktopper:~/",
    "ssh pi@desktopper \"unzip desktopper.zip -d desktopper;cd desktopper/resources; chmod +x target_deploy.sh; sudo ./target_deploy.sh; cd ~; rm -rf desktopper*\"",
    "echo Cleaning up",
    "rm -f desktopper.zip"
]

